/*
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one 
 * more letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 * 
 * Input:
 * s = "abcd"
 * t = "abcde"
 * 
 * Output:
 * e
 * 
 * Explanation:
 * 'e' is the letter that was added.
 */
public class FindTheDifference {

    public char findTheDifference(String s, String t) {
        char result = 0;
        for (int i = 0; i < s.length(); ++i) {
            result ^= s.charAt(i);
        }
        for (int i = 0; i < t.length(); ++i) {
            result ^= t.charAt(i);
        }
        return result;
    }

/*******************************************************************/

    public char findTheDifference(String s, String t) {
        int[] map = new int[256];
        for (int i = 0; i < t.length(); ++i) {
            map[t.charAt(i) - 'a']++;
            if (i < s.length()) {
                map[s.charAt(i) - 'a']--;
            }
        }
        char result = 0;
        for (int i = 0; i < map.length; ++i) {
            if (map[i] > 0) {
                result = (char) ('a' + i);
            }
        }
        return result;
    }

}
