'''
Each new term in the Fibonacci sequence is generated by adding
the previous two terms. By starting with 1 and 2, the first 10
terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values
do not exceed four million, find the sum of the even-valued terms.
'''
import time

__author__ = 'SUN'

def calculate():
    result, a, b = 0, 1, 1
    while b <= 4000000:
        a, b = b, a + b
        result += b if b % 2 == 0 else 0
    print(result)

if __name__ == '__main__':
    start = time.clock()
    calculate()
    print('Run time is', time.clock() - start)