"""
Pentagon numbers
Problem 44
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten
pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70
− 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of
D?
"""
import time

__date__ = '14-3-25'
__author__ = 'SUN'

def project_euler():
    pen = set()
    i = 1
    while True:
        next_pen = i * (3 * i - 1) // 2
        pen.add(next_pen)
        i += 1
        for p in pen:
            if (next_pen - p) in pen and (next_pen - 2 * p) in pen:
                return next_pen - 2 * p

if __name__ == '__main__':
    start = time.clock()
    print(project_euler())
    print('Runtime is ', time.clock() - start)